import * as vscode from 'vscode';
import { v4 as uuidv4 } from 'uuid';

/**
 * Status lifecycle for an agent instance
 * queued -> planning -> executing -> testing -> completed/failed
 * At any point, can be paused/cancelled
 */
export type AgentStatus = 'queued' | 'planning' | 'executing' | 'testing' | 'paused' | 'completed' | 'failed' | 'cancelled';

/**
 * Execution mode for the agent
 */
export type AgentMode = 'autopilot' | 'review' | 'assisted';

/**
 * Log levels for agent operations
 */
export type LogLevel = 'info' | 'warn' | 'error' | 'debug' | 'tool';

/**
 * Artifact types that agents can generate
 */
export type ArtifactType = 'plan' | 'code_diff' | 'screenshot' | 'browser_recording' | 'test_report' | 'task_list' | 'documentation';

/**
 * Comment on an artifact (Google Docs-style collaboration)
 */
export interface ArtifactComment {
    id: string;
    author: 'user' | 'agent';
    text: string;
    lineRef?: number;
    selection?: { start: number; end: number };
    resolved: boolean;
    createdAt: Date;
}

/**
 * Artifact generated by an agent
 */
export interface AgentArtifact {
    id: string;
    agentId: string;
    type: ArtifactType;
    title: string;
    content: string;
    metadata: Record<string, any>;
    createdAt: Date;
    comments: ArtifactComment[];
}

/**
 * Log entry for agent activities
 */
export interface AgentLog {
    timestamp: Date;
    level: LogLevel;
    message: string;
    toolName?: string;
    toolArgs?: Record<string, any>;
    toolResult?: any;
}

/**
 * User feedback on agent work
 */
export interface AgentFeedback {
    id: string;
    artifactId?: string;
    text: string;
    createdAt: Date;
    applied: boolean;
}

/**
 * Complete agent instance with all tracking information
 * Represents a single autonomous AI agent working on a task
 */
export interface AgentInstance {
    id: string;
    name: string;
    task: string;
    status: AgentStatus;
    mode: AgentMode;
    progress: number; // 0-100
    artifacts: AgentArtifact[];
    logs: AgentLog[];
    startedAt: Date;
    completedAt?: Date;
    feedback: AgentFeedback[];
    subAgents: string[]; // IDs of child agents
    workspace?: string;
    currentStep?: string;
    totalSteps?: number;
    completedSteps?: number;
    error?: string;
}

/**
 * Statistics about all agents in the system
 */
export interface AgentStats {
    total: number;
    active: number;
    completed: number;
    failed: number;
    queued: number;
    paused: number;
}

/**
 * Options for spawning a new agent
 */
export interface SpawnAgentOptions {
    name?: string;
    mode?: AgentMode;
    workspace?: string;
    maxSteps?: number;
}

/**
 * AgentManager - Mission Control for multi-agent orchestration
 *
 * Implements Google Antigravity-style "Mission Control" for spawning,
 * monitoring, and managing multiple autonomous AI agents working in parallel
 * on different tasks.
 *
 * Features:
 * - Spawn agents with configurable execution modes
 * - Monitor agent progress in real-time
 * - Track artifacts and provide Google Docs-style commenting
 * - Manage concurrent agent execution with configurable limits
 * - Pause, resume, and cancel agents
 * - Comprehensive logging and error handling
 */
export class AgentManager {
    private agents: Map<string, AgentInstance> = new Map();
    private maxConcurrentAgents: number = 5;
    private agentQueue: string[] = []; // Queue of agent IDs waiting to execute
    private disposed = false;

    // Event emitters for reactive UI updates
    private _onAgentUpdate: vscode.EventEmitter<AgentInstance> = new vscode.EventEmitter<AgentInstance>();
    public onAgentUpdate: vscode.Event<AgentInstance> = this._onAgentUpdate.event;

    private _onArtifactCreated: vscode.EventEmitter<AgentArtifact> = new vscode.EventEmitter<AgentArtifact>();
    public onArtifactCreated: vscode.Event<AgentArtifact> = this._onArtifactCreated.event;

    private _onAgentStatusChange: vscode.EventEmitter<{ agentId: string; status: AgentStatus }> = new vscode.EventEmitter();
    public onAgentStatusChange: vscode.Event<{ agentId: string; status: AgentStatus }> = this._onAgentStatusChange.event;

    private _onLogAdded: vscode.EventEmitter<{ agentId: string; log: AgentLog }> = new vscode.EventEmitter();
    public onLogAdded: vscode.Event<{ agentId: string; log: AgentLog }> = this._onLogAdded.event;

    constructor(maxConcurrentAgents: number = 5) {
        this.maxConcurrentAgents = Math.max(1, Math.min(maxConcurrentAgents, 20));
        this.validateState();
    }

    /**
     * Spawn a new agent with the given task and options
     * The agent is added to the queue and will start when resources are available
     */
    public spawnAgent(
        task: string,
        options?: SpawnAgentOptions
    ): AgentInstance {
        this.ensureNotDisposed();

        if (!task || task.trim().length === 0) {
            throw new Error('Agent task cannot be empty');
        }

        const agentId = uuidv4();
        const agent: AgentInstance = {
            id: agentId,
            name: options?.name || `Agent-${agentId.substring(0, 8)}`,
            task: task.trim(),
            status: 'queued',
            mode: options?.mode || 'autopilot',
            progress: 0,
            artifacts: [],
            logs: [],
            startedAt: new Date(),
            feedback: [],
            subAgents: [],
            workspace: options?.workspace,
            completedSteps: 0,
            totalSteps: options?.maxSteps || 10,
        };

        this.agents.set(agentId, agent);
        this.agentQueue.push(agentId);

        this.addLog(agentId, 'info', `Agent spawned with mode: ${agent.mode}`, undefined);
        this.emitAgentUpdate(agent);
        this.processQueue();

        return agent;
    }

    /**
     * Get a specific agent by ID
     */
    public getAgent(id: string): AgentInstance | undefined {
        return this.agents.get(id);
    }

    /**
     * Get all agents in the system
     */
    public getAllAgents(): AgentInstance[] {
        return Array.from(this.agents.values());
    }

    /**
     * Get only agents that are currently executing
     */
    public getActiveAgents(): AgentInstance[] {
        return Array.from(this.agents.values()).filter(agent =>
            ['planning', 'executing', 'testing'].includes(agent.status)
        );
    }

    /**
     * Get agents in a specific status
     */
    public getAgentsByStatus(status: AgentStatus): AgentInstance[] {
        return Array.from(this.agents.values()).filter(agent => agent.status === status);
    }

    /**
     * Pause an agent that's currently running
     */
    public pauseAgent(id: string): void {
        this.ensureNotDisposed();
        const agent = this.getAgent(id);
        if (!agent) {
            throw new Error(`Agent not found: ${id}`);
        }

        if (!['executing', 'planning', 'testing'].includes(agent.status)) {
            throw new Error(`Cannot pause agent in status: ${agent.status}`);
        }

        agent.status = 'paused';
        this.addLog(id, 'info', 'Agent paused by user');
        this.emitAgentUpdate(agent);
        this.emitStatusChange(id, 'paused');
    }

    /**
     * Resume a paused agent
     */
    public resumeAgent(id: string): void {
        this.ensureNotDisposed();
        const agent = this.getAgent(id);
        if (!agent) {
            throw new Error(`Agent not found: ${id}`);
        }

        if (agent.status !== 'paused') {
            throw new Error(`Cannot resume agent in status: ${agent.status}`);
        }

        agent.status = 'executing';
        this.addLog(id, 'info', 'Agent resumed by user');
        this.emitAgentUpdate(agent);
        this.emitStatusChange(id, 'executing');
    }

    /**
     * Cancel an agent's execution
     * Agent transitions to cancelled state and is removed from queue
     */
    public cancelAgent(id: string): void {
        this.ensureNotDisposed();
        const agent = this.getAgent(id);
        if (!agent) {
            throw new Error(`Agent not found: ${id}`);
        }

        if (agent.status === 'completed' || agent.status === 'failed' || agent.status === 'cancelled') {
            throw new Error(`Cannot cancel agent in status: ${agent.status}`);
        }

        agent.status = 'cancelled';
        agent.completedAt = new Date();
        this.addLog(id, 'info', 'Agent cancelled by user');

        // Remove from queue if still queued
        const queueIndex = this.agentQueue.indexOf(id);
        if (queueIndex >= 0) {
            this.agentQueue.splice(queueIndex, 1);
        }

        this.emitAgentUpdate(agent);
        this.emitStatusChange(id, 'cancelled');
        this.processQueue();
    }

    /**
     * Add user feedback to an agent
     */
    public addFeedback(agentId: string, feedbackText: string, artifactId?: string): void {
        this.ensureNotDisposed();
        const agent = this.getAgent(agentId);
        if (!agent) {
            throw new Error(`Agent not found: ${agentId}`);
        }

        if (!feedbackText || feedbackText.trim().length === 0) {
            throw new Error('Feedback text cannot be empty');
        }

        const feedback: AgentFeedback = {
            id: uuidv4(),
            artifactId,
            text: feedbackText.trim(),
            createdAt: new Date(),
            applied: false,
        };

        agent.feedback.push(feedback);
        this.addLog(agentId, 'info', `Feedback added: ${feedbackText.substring(0, 50)}...`, undefined);
        this.emitAgentUpdate(agent);
    }

    /**
     * Add a Google Docs-style comment to an artifact
     */
    public addComment(
        agentId: string,
        artifactId: string,
        comment: Omit<ArtifactComment, 'id' | 'createdAt'>
    ): void {
        this.ensureNotDisposed();
        const agent = this.getAgent(agentId);
        if (!agent) {
            throw new Error(`Agent not found: ${agentId}`);
        }

        const artifact = agent.artifacts.find(a => a.id === artifactId);
        if (!artifact) {
            throw new Error(`Artifact not found: ${artifactId}`);
        }

        if (!comment.text || comment.text.trim().length === 0) {
            throw new Error('Comment text cannot be empty');
        }

        const newComment: ArtifactComment = {
            ...comment,
            id: uuidv4(),
            createdAt: new Date(),
            text: comment.text.trim(),
        };

        artifact.comments.push(newComment);
        this.addLog(agentId, 'info', `Comment added to artifact ${artifactId}`, undefined);
        this.emitAgentUpdate(agent);
    }

    /**
     * Resolve/close a comment on an artifact
     */
    public resolveComment(agentId: string, artifactId: string, commentId: string): void {
        this.ensureNotDisposed();
        const agent = this.getAgent(agentId);
        if (!agent) {
            throw new Error(`Agent not found: ${agentId}`);
        }

        const artifact = agent.artifacts.find(a => a.id === artifactId);
        if (!artifact) {
            throw new Error(`Artifact not found: ${artifactId}`);
        }

        const comment = artifact.comments.find(c => c.id === commentId);
        if (!comment) {
            throw new Error(`Comment not found: ${commentId}`);
        }

        comment.resolved = true;
        this.addLog(agentId, 'info', `Comment resolved: ${commentId}`, undefined);
        this.emitAgentUpdate(agent);
    }

    /**
     * Create a new artifact for an agent
     */
    public createArtifact(
        agentId: string,
        artifact: Omit<AgentArtifact, 'id' | 'createdAt' | 'comments'>
    ): AgentArtifact {
        this.ensureNotDisposed();
        const agent = this.getAgent(agentId);
        if (!agent) {
            throw new Error(`Agent not found: ${agentId}`);
        }

        if (!artifact.title || artifact.title.trim().length === 0) {
            throw new Error('Artifact title cannot be empty');
        }

        const newArtifact: AgentArtifact = {
            ...artifact,
            id: uuidv4(),
            createdAt: new Date(),
            comments: [],
        };

        agent.artifacts.push(newArtifact);
        this.addLog(agentId, 'info', `Artifact created: ${newArtifact.title}`, undefined);
        this.emitArtifactCreated(newArtifact);
        this.emitAgentUpdate(agent);

        return newArtifact;
    }

    /**
     * Update an artifact's content
     */
    public updateArtifact(
        agentId: string,
        artifactId: string,
        updates: { content?: string; metadata?: Record<string, any> }
    ): void {
        this.ensureNotDisposed();
        const agent = this.getAgent(agentId);
        if (!agent) {
            throw new Error(`Agent not found: ${agentId}`);
        }

        const artifact = agent.artifacts.find(a => a.id === artifactId);
        if (!artifact) {
            throw new Error(`Artifact not found: ${artifactId}`);
        }

        if (updates.content !== undefined) {
            artifact.content = updates.content;
        }

        if (updates.metadata !== undefined) {
            artifact.metadata = { ...artifact.metadata, ...updates.metadata };
        }

        this.addLog(agentId, 'info', `Artifact updated: ${artifactId.substring(0, 8)}`, undefined);
        this.emitAgentUpdate(agent);
    }

    /**
     * Update the progress of an agent
     */
    public updateAgentProgress(agentId: string, progress: number, currentStep?: string): void {
        this.ensureNotDisposed();
        const agent = this.getAgent(agentId);
        if (!agent) {
            throw new Error(`Agent not found: ${agentId}`);
        }

        const validProgress = Math.max(0, Math.min(100, progress));
        agent.progress = validProgress;

        if (currentStep !== undefined) {
            agent.currentStep = currentStep;
            if (agent.completedSteps === undefined) {
                agent.completedSteps = 0;
            }
            if (agent.totalSteps && agent.completedSteps < agent.totalSteps) {
                agent.completedSteps = Math.ceil((validProgress / 100) * agent.totalSteps);
            }
        }

        this.emitAgentUpdate(agent);
    }

    /**
     * Update an agent's status
     */
    public updateAgentStatus(agentId: string, status: AgentStatus): void {
        this.ensureNotDisposed();
        const agent = this.getAgent(agentId);
        if (!agent) {
            throw new Error(`Agent not found: ${agentId}`);
        }

        const previousStatus = agent.status;
        agent.status = status;

        if (status === 'completed' || status === 'failed' || status === 'cancelled') {
            agent.completedAt = new Date();
        }

        this.addLog(agentId, 'info', `Status changed: ${previousStatus} -> ${status}`, undefined);
        this.emitStatusChange(agentId, status);
        this.emitAgentUpdate(agent);

        // If agent finished, process queue for next agent
        if (previousStatus !== 'queued' && (status === 'completed' || status === 'failed' || status === 'cancelled')) {
            this.processQueue();
        }
    }

    /**
     * Add a log entry to an agent
     */
    public addLog(
        agentId: string,
        level: LogLevel,
        message: string,
        toolInfo?: { name: string; args?: Record<string, any>; result?: any }
    ): void {
        const agent = this.getAgent(agentId);
        if (!agent) {
            console.warn(`Cannot add log to non-existent agent: ${agentId}`);
            return;
        }

        const log: AgentLog = {
            timestamp: new Date(),
            level,
            message,
            toolName: toolInfo?.name,
            toolArgs: toolInfo?.args,
            toolResult: toolInfo?.result,
        };

        agent.logs.push(log);

        // Keep logs bounded to prevent memory issues
        if (agent.logs.length > 1000) {
            agent.logs = agent.logs.slice(-500);
        }

        this.emitLogAdded(agentId, log);
    }

    /**
     * Set an error on an agent
     */
    public setAgentError(agentId: string, error: string | Error): void {
        this.ensureNotDisposed();
        const agent = this.getAgent(agentId);
        if (!agent) {
            throw new Error(`Agent not found: ${agentId}`);
        }

        const errorMessage = error instanceof Error ? error.message : error;
        agent.error = errorMessage;
        agent.status = 'failed';
        agent.completedAt = new Date();

        this.addLog(agentId, 'error', `Agent failed: ${errorMessage}`, undefined);
        this.emitStatusChange(agentId, 'failed');
        this.emitAgentUpdate(agent);
        this.processQueue();
    }

    /**
     * Spawn a sub-agent (child agent) for a specific task
     * Useful for parallelizing work like browser automation, testing, etc.
     */
    public spawnSubAgent(parentAgentId: string, task: string, name: string): AgentInstance {
        this.ensureNotDisposed();
        const parent = this.getAgent(parentAgentId);
        if (!parent) {
            throw new Error(`Parent agent not found: ${parentAgentId}`);
        }

        const subAgent = this.spawnAgent(task, {
            name: `${parent.name}/${name}`,
            mode: parent.mode,
            workspace: parent.workspace,
        });

        parent.subAgents.push(subAgent.id);
        this.addLog(parentAgentId, 'info', `Sub-agent spawned: ${subAgent.name}`, undefined);
        this.emitAgentUpdate(parent);

        return subAgent;
    }

    /**
     * Get aggregate statistics about all agents
     */
    public getAgentStats(): AgentStats {
        const agents = this.getAllAgents();
        return {
            total: agents.length,
            active: agents.filter(a => ['planning', 'executing', 'testing'].includes(a.status)).length,
            completed: agents.filter(a => a.status === 'completed').length,
            failed: agents.filter(a => a.status === 'failed').length,
            queued: agents.filter(a => a.status === 'queued').length,
            paused: agents.filter(a => a.status === 'paused').length,
        };
    }

    /**
     * Get detailed metrics for an agent
     */
    public getAgentMetrics(agentId: string) {
        const agent = this.getAgent(agentId);
        if (!agent) {
            return null;
        }

        const duration = agent.completedAt
            ? agent.completedAt.getTime() - agent.startedAt.getTime()
            : Date.now() - agent.startedAt.getTime();

        return {
            agentId,
            duration,
            durationSeconds: Math.round(duration / 1000),
            artifacts: agent.artifacts.length,
            logs: agent.logs.length,
            feedback: agent.feedback.length,
            unresolvedComments: agent.artifacts.reduce((acc, art) => acc + art.comments.filter(c => !c.resolved).length, 0),
            progress: agent.progress,
            subAgentsCount: agent.subAgents.length,
        };
    }

    /**
     * Export agent data for debugging or analysis
     */
    public exportAgentData(agentId: string): any {
        const agent = this.getAgent(agentId);
        if (!agent) {
            return null;
        }

        return {
            ...agent,
            startedAt: agent.startedAt.toISOString(),
            completedAt: agent.completedAt?.toISOString(),
            logs: agent.logs.map(log => ({
                ...log,
                timestamp: log.timestamp.toISOString(),
            })),
            artifacts: agent.artifacts.map(artifact => ({
                ...artifact,
                createdAt: artifact.createdAt.toISOString(),
                comments: artifact.comments.map(c => ({
                    ...c,
                    createdAt: c.createdAt.toISOString(),
                })),
            })),
            feedback: agent.feedback.map(f => ({
                ...f,
                createdAt: f.createdAt.toISOString(),
            })),
        };
    }

    /**
     * Clear completed agents to free memory
     */
    public clearCompletedAgents(): number {
        this.ensureNotDisposed();
        const completedIds: string[] = [];

        this.agents.forEach((agent, id) => {
            if (agent.status === 'completed' || agent.status === 'cancelled') {
                completedIds.push(id);
            }
        });

        completedIds.forEach(id => {
            this.agents.delete(id);
        });

        return completedIds.length;
    }

    /**
     * Dispose of the manager and clean up resources
     */
    public dispose(): void {
        if (this.disposed) {
            return;
        }

        // Cancel all running agents
        this.getAllAgents().forEach(agent => {
            if (!['completed', 'failed', 'cancelled'].includes(agent.status)) {
                try {
                    this.cancelAgent(agent.id);
                } catch (e) {
                    // Agent may have already been disposed
                }
            }
        });

        this.agents.clear();
        this.agentQueue = [];

        this._onAgentUpdate.dispose();
        this._onArtifactCreated.dispose();
        this._onAgentStatusChange.dispose();
        this._onLogAdded.dispose();

        this.disposed = true;
    }

    /**
     * Check if the manager is disposed
     */
    public isDisposed(): boolean {
        return this.disposed;
    }

    // ==================== Private Methods ====================

    /**
     * Process the agent queue and start agents when resources are available
     */
    private processQueue(): void {
        if (this.disposed) {
            return;
        }

        const activeCount = this.getActiveAgents().length;
        const availableSlots = this.maxConcurrentAgents - activeCount;

        for (let i = 0; i < availableSlots && this.agentQueue.length > 0; i++) {
            const agentId = this.agentQueue.shift();
            if (!agentId) break;

            const agent = this.getAgent(agentId);
            if (!agent) continue;

            if (agent.status === 'queued') {
                agent.status = 'planning';
                this.addLog(agentId, 'info', 'Agent started - entering planning phase', undefined);
                this.emitStatusChange(agentId, 'planning');
                this.emitAgentUpdate(agent);
            }
        }
    }

    /**
     * Emit agent update event
     */
    private emitAgentUpdate(agent: AgentInstance): void {
        if (!this.disposed) {
            this._onAgentUpdate.fire(agent);
        }
    }

    /**
     * Emit artifact created event
     */
    private emitArtifactCreated(artifact: AgentArtifact): void {
        if (!this.disposed) {
            this._onArtifactCreated.fire(artifact);
        }
    }

    /**
     * Emit status change event
     */
    private emitStatusChange(agentId: string, status: AgentStatus): void {
        if (!this.disposed) {
            this._onAgentStatusChange.fire({ agentId, status });
        }
    }

    /**
     * Emit log added event
     */
    private emitLogAdded(agentId: string, log: AgentLog): void {
        if (!this.disposed) {
            this._onLogAdded.fire({ agentId, log });
        }
    }

    /**
     * Ensure the manager is not disposed
     */
    private ensureNotDisposed(): void {
        if (this.disposed) {
            throw new Error('AgentManager has been disposed');
        }
    }

    /**
     * Validate internal state
     */
    private validateState(): void {
        if (this.maxConcurrentAgents < 1) {
            throw new Error('maxConcurrentAgents must be at least 1');
        }
    }
}

/**
 * Singleton instance of AgentManager for the extension
 * Can be instantiated as needed or used as a singleton
 */
let agentManagerInstance: AgentManager | undefined;

/**
 * Get or create the singleton AgentManager instance
 */
export function getAgentManager(maxConcurrentAgents?: number): AgentManager {
    if (!agentManagerInstance) {
        agentManagerInstance = new AgentManager(maxConcurrentAgents);
    }
    return agentManagerInstance;
}

/**
 * Reset the singleton instance (primarily for testing)
 */
export function resetAgentManager(): void {
    if (agentManagerInstance) {
        agentManagerInstance.dispose();
        agentManagerInstance = undefined;
    }
}
